#############################################################################
# Makefile for building: cervellone
# Generated by qmake (2.01a) (Qt 4.8.1) on: Mon Sep 30 10:24:57 2013
# Project:  ../cervellone/cervellone.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug -o Makefile ../cervellone/cervellone.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_PHONON_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I../cervellone -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/phonon -I/usr/include/qt4 -I/usr/include/qt4/phonon_compat -I. -I. -I../cervellone -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lphonon -lQtSql -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../cervellone/main.cpp \
		../cervellone/cervellone.cpp \
		../cervellone/database_controller.cpp \
		../cervellone/question.cpp \
		../cervellone/hello_window.cpp moc_cervellone.cpp \
		moc_hello_window.cpp
OBJECTS       = main.o \
		cervellone.o \
		database_controller.o \
		question.o \
		hello_window.o \
		moc_cervellone.o \
		moc_hello_window.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		../cervellone/cervellone.pro
QMAKE_TARGET  = cervellone
DESTDIR       = 
TARGET        = cervellone

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_cervellone.h ui_hello_window.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: ../cervellone/cervellone.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug -o Makefile ../cervellone/cervellone.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug -o Makefile ../cervellone/cervellone.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/cervellone1.0.0 || $(MKDIR) .tmp/cervellone1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/cervellone1.0.0/ && $(COPY_FILE) --parents ../cervellone/cervellone.h ../cervellone/database_controller.h ../cervellone/question.h ../cervellone/hello_window.h .tmp/cervellone1.0.0/ && $(COPY_FILE) --parents ../cervellone/main.cpp ../cervellone/cervellone.cpp ../cervellone/database_controller.cpp ../cervellone/question.cpp ../cervellone/hello_window.cpp .tmp/cervellone1.0.0/ && $(COPY_FILE) --parents ../cervellone/cervellone.ui ../cervellone/hello_window.ui .tmp/cervellone1.0.0/ && (cd `dirname .tmp/cervellone1.0.0` && $(TAR) cervellone1.0.0.tar cervellone1.0.0 && $(COMPRESS) cervellone1.0.0.tar) && $(MOVE) `dirname .tmp/cervellone1.0.0`/cervellone1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/cervellone1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_cervellone.cpp moc_hello_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cervellone.cpp moc_hello_window.cpp
moc_cervellone.cpp: ../cervellone/database_controller.h \
		../cervellone/question.h \
		../cervellone/hello_window.h \
		../cervellone/cervellone.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../cervellone/cervellone.h -o moc_cervellone.cpp

moc_hello_window.cpp: ../cervellone/hello_window.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../cervellone/hello_window.h -o moc_hello_window.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_cervellone.h ui_hello_window.h
compiler_uic_clean:
	-$(DEL_FILE) ui_cervellone.h ui_hello_window.h
ui_cervellone.h: ../cervellone/cervellone.ui
	/usr/bin/uic-qt4 ../cervellone/cervellone.ui -o ui_cervellone.h

ui_hello_window.h: ../cervellone/hello_window.ui
	/usr/bin/uic-qt4 ../cervellone/hello_window.ui -o ui_hello_window.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../cervellone/main.cpp ../cervellone/cervellone.h \
		../cervellone/database_controller.h \
		../cervellone/question.h \
		../cervellone/hello_window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../cervellone/main.cpp

cervellone.o: ../cervellone/cervellone.cpp ../cervellone/cervellone.h \
		../cervellone/database_controller.h \
		../cervellone/question.h \
		../cervellone/hello_window.h \
		ui_cervellone.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cervellone.o ../cervellone/cervellone.cpp

database_controller.o: ../cervellone/database_controller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database_controller.o ../cervellone/database_controller.cpp

question.o: ../cervellone/question.cpp ../cervellone/question.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o question.o ../cervellone/question.cpp

hello_window.o: ../cervellone/hello_window.cpp ../cervellone/hello_window.h \
		ui_hello_window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hello_window.o ../cervellone/hello_window.cpp

moc_cervellone.o: moc_cervellone.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cervellone.o moc_cervellone.cpp

moc_hello_window.o: moc_hello_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hello_window.o moc_hello_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

